Added support for school notices bigger than 4096 characters
staszicwaw/eten-librus-standalone pull request #1
Opened 2023-05-12 06:18 UTC by patgra1410

2023-05-12 19:43 UTC, mikimasn commented
According to [discord documentation](https://github.com/staszicwaw/eten-librus-standalone/pulls) the total number of characters in all embeds must be less than 6000. Your code does not respect these limits, which may lead to errors when sending the message

2023-05-12 20:20 UTC, peonii requested changes
napraw formatowanie bo wyglada strasznie

2023-05-12 20:21 UTC, peonii commented
albo wsm ja to zrobie

2023-05-14 20:00 UTC, MasloMaslane requested changes
Pomijając to, że suma znaków w embedach ma być <= 6000, jest dobrze pzoa tym:

2023-05-14 20:00 UTC, MasloMaslane commented on src/librusManager.ts
> +		while (embedDesc.length > 0) {
Czy jakby była wiadomość która jest krótsza od 4096 znaków i nie kończy się \n to to nie wyśle dwóch embedów?

2023-05-14 20:46 UTC, patgra1410 commented on src/librusManager.ts
> +		while (embedDesc.length > 0) {
Fakty

2023-05-14 21:06 UTC, patgra1410 commented
Przetestowałem to i rzeczywiście jak jest suma znaków > 6000 to jest DiscordAPIError

2023-05-14 21:09 UTC, MasloMaslane commented
> Przetestowałem to i rzeczywiście jak jest suma znaków > 6000 to jest DiscordAPIError

To sie kiedys naprawi, na razie mozna dodac co jest

2023-05-14 21:09 UTC, MasloMaslane approved these changes

2023-05-14 21:14 UTC, patgra1410 commented
> > Przetestowałem to i rzeczywiście jak jest suma znaków > 6000 to jest DiscordAPIError
> 
> To sie kiedys naprawi, na razie mozna dodac co jest

Może zanim ktoś naprawi to discord zwiększy limit (nie liczyłbym na to xD)

2023-05-14 21:14 UTC, MasloMaslane commented
Ale wsm warto pewnie dodać ucinanie do 6k znaków żeby zawsze coś wysyłało

2023-05-14 21:30 UTC, MasloMaslane approved these changes
Pięknie

2023-05-15 12:24 UTC, merged